Repository mindslab-ai/mindslab-ai.github.io, pull requests merged in 2022-08, with the labels that each got.

#33 make templates for updating publications easily
  src/components/PublicationFeatures/index.js
  src/pages/publications.mdx
Labels: tech blog

#35 make templates for updating open-sources easily
  src/components/OpenSourceFeatures/index.js
  src/pages/open-source.mdx
Labels: tech blog

#37 add a description for adding publication or open-source
  README.md
Labels: documentation, tech blog

#38 assem-vc
  blog/2022-08-19-publication-assem-vc/image/overall.png
  blog/2022-08-19-publication-assem-vc/image/results.png
  blog/2022-08-19-publication-assem-vc/image/singing_control.png
  blog/2022-08-19-publication-assem-vc/image/singing_overall.png
  blog/2022-08-19-publication-assem-vc/image/speaker_disentanglement.png
  blog/2022-08-19-publication-assem-vc/index.mdx
  blog/authors.yml
Labels: content
